### PR TITLE
Add LwDITA @format values

### PR DESCRIPTION
**Pull request by ahouser**
Added values for LwDITA topics and maps; added "markdown" value; wc: changed "linked-to" to "referenced".

### CODE REVIEW

**Comment by robander** [comment]
This removes the following statement:
> For other formats, using the file extension without the "." character typically represents the format.

Is that no longer applicable / an intended change? I'm pretty sure that advice still stands, it's just that `markdown` doesn't quite fit the pattern?

**Comment by ahouser** [comment]
Hi Robert,

Your assessment is correct ... "markdown" (which the DITA-OT supports) does
not fit the pattern. I struggled a bit with how to express this, without
getting twisted and awkward. My final conclusion was that the "pattern"
isn't very important, for only three of four file types (and, one could
argue that HTML files with a suffix of ".htm" do not fit the pattern).

I'm still learning the art of writing spec content, so feel free to decline
the pull request if you think I/we should express this differently.

Thx!

-Alan

**Comment by robander** [comment]
My gut reaction is that the pattern is important -- it's one that still comes up regularly for me even after 15 years, with people asking "what should I put in format for this XYZ file type?" While it's definitely not a formal rule (and shouldn't be), I think the current "typically" language already allows wiggle room. I sort of like having `markdown` in there to highlight that it's not an absolute pattern.

As to the pull request: no reason to decline it, if you push another commit to restore that line it's probably going to be fine.

**Comment by robander** [comment]
Closing this one because it's obsolete, superseded by #251 

(As a side note - you can add commits to change an existing pull request just by pushing to the same branch -- you don't need to create a new branch / open a new pull request.)

**Pull request closed without merging**
