### PR TITLE
Updated format attribute for LwDITA; retained file extension text.

### PR DESCRIPTION
**Pull request by ahouser**

### CODE REVIEW

**Comment by robander** [comment]
The new updates change more than I expected -- is there a reason you globally changed "linked-to" to "referenced"? It introduces a bit of ambiguity and awkward language into at least one spot --
> The referenced resource is a DITA map. It represents the referenced hierarchy at the current point in the referencing map.
(I say ambiguity because with that update, the referenced resource becomes both the map document itself as well as the hierarchy within that map.)

I also don't think we should add the new sentence:
> DITA processors may recognize other values of `<xmlatt>`format`</xmlatt>` for special processing.
That uses the "may" term which -- as much as possible -- we're trying to remove from context where it is not RFC normative terminology. The sentence as a whole also does not add anything meaningful - processors can really recognize values of any attribute for special processing.

Final comment on the change -- I don't think we need a whole separate section for LwDITA tokens. As written now, it calls those out of interest only to processors that support LwDITA, but the meaning of those tokens is the same regardless of what formats are supported -- just as `format="pdf"` always means the same thing, regardless of whether a processor can do anything meaningful with it.

With that in mind - I think the simpler / easier approach is just to list the tokens along with other sample values? For example, something like this could be placed into the existing set of sample formats without the need for other new language or restructuring:
```
<dlentry>
  <dt>xdita</dt>
  <dd>The format of the referenced resource is XDITA (Lightweight DITA's XML representation).</dd>
</dlentry>
```

**Comment by ahouser** [comment]
Apologies for letting this age ...

My objection to "linked-to" is that it's a new term, that means exactly the same thing as an existing well-known term. (Would a translator stumble over the distinction between "linked-to" and "referenced"?). 

> The referenced resource is a DITA map. It represents the referenced hierarchy at the current point in the referencing map.
> (I say ambiguity because with that update, the referenced resource becomes both the map document itself as well as the hierarchy within that map.)

Would something like this be more clear?

> The specified resource is a DITA map. It represents the referenced hierarchy at the current point in the referencing map.

or 

> The resource is a DITA map. It specifies the referenced hierarchy at the current point in the referencing map.

I can agree to separate the LwDITA tokens. I think grouping them does provide meaningful and useful context, but we can do that for each individual LwDITA token, as you have in your suggested re-write.

**Comment by keberlein** [comment]
I think the topic needs to be overhauled -- overdue for a complete edit.

**Comment by ahouser** [comment]
> I think the topic needs to be overhauled -- overdue for a complete edit.

OK ... I'm curious to know what you have in mind.

**Comment by keberlein** [comment]
I think, as currently written, the topic attempts to cover too much:

1. Reference information for the format attribute
2. Information about how processors should handle <topicref> elements that do not have a explicit value for the format attribute

I think if we treat those two items separately -- The first here in the element reference topic, and the second in the architectural topics about "DITA map processing" -- it will work better. Thoughts, @robander and @ahouser ?

**Comment by ahouser** [comment]
Apologies ... I had this slotted in my "done" category.

Looking at the draft 2.0 "DITA Map Processing" section, I could see splitting this information, if that is consistent with our general approach for the DITA 2.0 spec.

**Comment by ahouser** [comment]
Closing this pull request. Opening new pull request that addresses only the original action item.

**Pull request closed without merging**
